name: iOS Build and Test

on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=15.4.0,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          xcodebuild clean build -project Photoquest.xcodeproj -scheme Photoquest -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
      - name: Test
        run: |
          xcodebuild clean test -project Photoquest.xcodeproj -scheme PhotoquestTests -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
