name: iOS Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=15.0,name=iPhone 13']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select latest stable Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Install simulator
        run: xcversion simulators --install='iOS 15.0'
      - name: Prepare simulator
        run: |
          sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
          sudo ln -s /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 15.0.simruntime
          xcrun simctl list runtimes
          xcrun simctl create iPhone_13 "iPhone 13" "com.apple.CoreSimulator.SimRuntime.iOS-15-0"
          xcrun simctl list devices 15.0
      - name: Show build settings
        run: xcodebuild -project Photoquest.xcodeproj -scheme Photoquest -showBuildSettings
      - name: Build
        run: xcodebuild clean build -project Photoquest.xcodeproj -scheme Photoquest -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
      - name: Test
        run: xcodebuild clean test -project Photoquest.xcodeproj -scheme PhotoquestTests -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
