name: Swift

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: fwal/setup-swift@v1
      with:
        swift-version: "5.6.0"
    - name: Build
      run: cd Photoquest && swift build -v
    - name: Run tests
      run: cd Photoquest && swift test -v
